In [3]:
#Importing PyTorch From https://pytorch.org/ website where PyTorch Build  Stable (1.9.0) OS Linux Package Pip Language Python Compute Platform CPU
!pip install torch==1.9.0+cpu torchvision==0.10.0+cpu torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [4]:
import torch

In [5]:
torch.__version__

'1.9.0+cpu'

<h3>Tensor is same like numpy array or nd-array

In [6]:
a= torch.tensor([[1,2],[3,4]])
print(a)

tensor([[1, 2],
        [3, 4]])


In [7]:
type(a)

torch.Tensor

<h2>In torch we can do the same operations of numpy

In [8]:
#To make a zero array of row 4 & col 4

In [9]:
a_Zero = torch.zeros(4,4)
print(a_Zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
#To make a one array of row 4 & col 4

In [11]:
a_One = torch.ones(4,4)
print(a_One)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
#To make an array of random values with row 4 & col 4

In [13]:
Ran = torch.rand(4,4)
print(Ran)

tensor([[0.5696, 0.8716, 0.8238, 0.7100],
        [0.2218, 0.6155, 0.3289, 0.7635],
        [0.7523, 0.8196, 0.9379, 0.3477],
        [0.2635, 0.2365, 0.2519, 0.4531]])


In [14]:
#Addition Operation
a1 = torch.rand(2 , 2)
a2 = torch.rand(2 , 2)

In [15]:
print(a1)

tensor([[0.1955, 0.8971],
        [0.8407, 0.5009]])


In [16]:
print(a2)

tensor([[0.5283, 0.0977],
        [0.5452, 0.7491]])


<h5> Will use 3 method to add a1 with a2

In [17]:
print(a1 + a2)

tensor([[0.7237, 0.9948],
        [1.3859, 1.2500]])


In [18]:
print(a1.add(a2))

tensor([[0.7237, 0.9948],
        [1.3859, 1.2500]])


In [19]:
#Here a1 will be equals to a1 + a2
a1.add_(a2)

tensor([[0.7237, 0.9948],
        [1.3859, 1.2500]])

In [20]:
a1

tensor([[0.7237, 0.9948],
        [1.3859, 1.2500]])